environment:
  matrix:
    - PYTHON: "C:\\Python27"
      TOXENV: "py27"

    - PYTHON: "C:\\Python33"
      TOXENV: "py33"

    - PYTHON: "C:\\Python34"
      TOXENV: "py34"

    - PYTHON: "C:\\Python35"
      TOXENV: "py35"

    - PYTHON: "C:\\Python27-x64"
      TOXENV: "py27"

    - PYTHON: "C:\\Python33-x64"
      TOXENV: "py33"

    - PYTHON: "C:\\Python34-x64"
      TOXENV: "py34"

    - PYTHON: "C:\\Python35-x64"
      TOXENV: "py35"

install:
    cmd: "%PYTHON%\\python.exe -m pip install tox"
build: off
test_script:
    "%PYTHON%/Scripts/tox.exe -e %TOXENV%"
